name: CI

on:
  push:
    paths:
      - "chia-poker/**"
  pull_request:
    paths:
      - "chia-poker/**"

defaults:
  run:
    working-directory: chia-poker

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Typecheck
        run: pnpm typecheck
